### ISSUE TITLE
Little mistake in slick.js

### ISSUE THREAD

**Issue by itkin** [liquidm/slickgrid-rails#1]
line 2 should be

//= require jquery/event/drag

instead of 

//= require jquery/event.drag

... but still i have to copy the jquery-plugins-rails javascript forler in my vendor/assets to load theese gem's files from my manifest do you have the same behavior (i'm on rails rails-3.2.0 and sprockets-2.1.2)

**Comment by hollow** [comment]
this has already been fixed in f3ef3893. regarding the jquery-plugins-rails gem: i don't need to copy them anywhere. sprockets should pick them up by itself ...

**Comment by diegodorado** [comment]
there is still an omission: docs says nothing about requiring these files

**Comment by diegodorado** [comment]
shouldn't gem 'jquery-plugins-rails' be a dependency ?

**Comment by AlJohri** [comment]
This should indeed by a dependency as far as my testing.

**Comment by stanchiang** [comment]
i had the same issue:
ended up copying jquery folder from "jquery-plugins-rails-0.1.1\vendor\assets\javascripts"
into "slickgrid-rails-0.2.0\vendor\assets\javascripts" folder.
